#!/bin/sh

g++ -o pupilImgTest testPupilImg.cpp ../src/eye/tracker.cpp ../src/pupil/tracker.cpp ../src/eye/haardetection.cpp ../src/pupil/contourdetection.cpp `pkg-config --cflags --libs opencv`

./pupilImgTest
